# common/config.py
"""
Central configuration file for default parameters.
"""

# --- RiskGuard Defaults ---
DEFAULT_RISKGUARD_PORT: int = 8080
DEFAULT_RISKGUARD_URL: str = f"http://127.0.0.1:{DEFAULT_RISKGUARD_PORT}"
DEFAULT_RISKGUARD_MAX_POS_SIZE: float = 10000.0
DEFAULT_RISKGUARD_MAX_CONCENTRATION: float = 0.50

# --- AlphaBot Defaults ---
DEFAULT_ALPHABOT_PORT: int = 8081
DEFAULT_ALPHABOT_URL: str = f"http://127.0.0.1:{DEFAULT_ALPHABOT_PORT}"
DEFAULT_ALPHABOT_SHORT_SMA: int = 5
DEFAULT_ALPHABOT_LONG_SMA: int = 30
DEFAULT_ALPHABOT_TRADE_QTY: int = 100
DEFAULT_ALPHABOT_TRADE_DECISION_ARTIFACT_NAME: str = "trade_decision"

# --- Simulator Defaults ---
DEFAULT_SIMULATOR_PORT: int = 8000
DEFAULT_SIMULATOR_URL: str = f"http://127.0.0.1:{DEFAULT_SIMULATOR_PORT}"
DEFAULT_SIM_DAYS: int = 100
DEFAULT_SIM_INITIAL_CASH: float = 100000.0
DEFAULT_SIM_INITIAL_PRICE: float = 100.0
DEFAULT_SIM_VOLATILITY: float = 0.02
DEFAULT_SIM_TREND: float = 0.0005

# --- Ticker Symbol ---
DEFAULT_TICKER: str = "TECH"
